### ISSUE TITLE
austingil.com

### ISSUE THREAD

**Issue by simevidas** [simevidas/web-dev-feeds#32]
Blog: https://austingil.com/blog/
Feed: https://austingil.com/feed/

<img width="669" alt="Screen Shot 2021-01-17 at 8 24 42 PM" src="https://user-images.githubusercontent.com/716405/104853656-8b7d8d80-5902-11eb-9743-78c372f20332.png">

**Comment by AustinGil** [comment]
Thanks for pointing this out. Is it fixed now?

**Comment by simevidas** [comment]
I’m still getting the same error. Could you check what you see when you open https://austingil.com/feed/?

**Comment by AustinGil** [comment]
That's weird. Im getting an XML feed. But maybe it's some sort of caching issue. Can you try now.

**Comment by simevidas** [comment]
I tested the URL on WebPageTest (Dulles location) to remove the possibility that the issue is present only my machine. 

https://www.webpagetest.org/result/210119_DiQZ_af0359aad5ce824286da8c67d76a4f79/

The error is still there (take a look at the screenshots).

The response is HTTP code 500, so maybe you can find out more if you have access to your server logs.

**Comment by AustinGil** [comment]
Ok, I think you were right. Proxy service showed it down. Can you try one more time for me?

**Comment by simevidas** [comment]
The feed is back 🎉
